{{- if .Values.grafana.ingress.enabled }}
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: grafana-stripprefix
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "monitoring.fullLabels" "grafana" | nindent 4 }}
spec:
  stripPrefix:
    prefixes:
      - /grafana
{{- end }}
