helm:
  parameters:
  - name: image.repository
    value: 771826808455.dkr.ecr.eu-west-1.amazonaws.com/public-api
    forcestring: true
  - name: image.tag
    value: f974bd7e876fa2218b556cc1b22bdaf7ae32b6d1-r1
    forcestring: true
