/**
 * @format
 * EMF (Embedded Metric Format) Custom Metrics Module
 *
 * Provides typed, structured CloudWatch metric emission for the
 * Bedrock content pipeline. Uses EMF format — CloudWatch automatically
 * extracts metrics from structured JSON logs without any SDK calls.
 *
 * Namespace: `BedrockPublisher`
 *
 * @see https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch_Embedded_Metric_Format.html
 */

// =============================================================================
// TYPES
// =============================================================================

/**
 * Complexity tier classification (mirrors index.ts ComplexityTier).
 * Re-declared here to avoid circular dependency.
 */
type ComplexityTier = 'LOW' | 'MID' | 'HIGH';

/**
 * Pipeline stage identifiers for failure tracking.
 * Each stage maps to a distinct phase of the content pipeline.
 */
export type FailureStage =
    | 'read-draft'
    | 'kb-retrieval'
    | 'complexity-analysis'
    | 'bedrock-converse'
    | 'parse-response'
    | 'validate-content'
    | 'qa-validation'
    | 's3-write'
    | 'dynamodb-write'
    | 'isr-revalidation';

/**
 * Token usage breakdown from a Bedrock Converse API response.
 */
export interface TokenUsage {
    /** Tokens sent to the model (prompt + system) */
    readonly inputTokens: number;
    /** Tokens generated by the model (response body) */
    readonly outputTokens: number;
    /** Thinking tokens consumed by Adaptive Thinking */
    readonly thinkingTokens: number;
}

/**
 * Complete pipeline execution context for EMF metric emission.
 */
export interface PipelineMetricsContext {
    /** Runtime environment (e.g. 'development', 'production') */
    readonly environment: string;
    /** Foundation model identifier (e.g. 'eu.anthropic.claude-sonnet-4-6') */
    readonly model: string;
    /** Article slug (high-cardinality — logged but not a dimension) */
    readonly slug: string;
    /** Pipeline mode: 'kb-augmented' or 'legacy-transform' */
    readonly mode: 'kb-augmented' | 'legacy-transform';
    /** Token usage from Bedrock response */
    readonly tokenUsage: TokenUsage;
    /** Stage timing measurements in milliseconds */
    readonly stageDurations: StageDurations;
    /** Complexity tier classification */
    readonly complexityTier: ComplexityTier;
    /** AI-scored technical confidence (0–100) */
    readonly technicalConfidence: number;
    /** Input draft size in bytes */
    readonly draftSizeBytes: number;
    /** QA validation score (0-100), if QA agent was run */
    readonly qaScore?: number;
    /** QA agent processing duration in ms, if applicable */
    readonly qaDurationMs?: number;
}

/**
 * Per-stage duration measurements in milliseconds.
 */
export interface StageDurations {
    /** Total end-to-end pipeline duration */
    readonly totalMs: number;
    /** Time spent reading the draft from S3 */
    readonly readDraftMs?: number;
    /** Time spent on KB retrieval (KB-augmented mode only) */
    readonly kbRetrievalMs?: number;
    /** Time spent calling the Bedrock Converse API */
    readonly bedrockConverseMs?: number;
    /** Time spent parsing the Bedrock response */
    readonly parseResponseMs?: number;
    /** Time spent on QA validation (2-agent PoC) */
    readonly qaValidationMs?: number;
    /** Time spent writing results to S3 */
    readonly s3WriteMs?: number;
    /** Time spent writing metadata to DynamoDB */
    readonly dynamoWriteMs?: number;
}

/**
 * Failure context for error-path metric emission.
 */
export interface FailureMetricsContext {
    /** Runtime environment */
    readonly environment: string;
    /** Foundation model identifier */
    readonly model: string;
    /** Pipeline stage where the failure occurred */
    readonly failureStage: FailureStage;
    /** Article slug, if known at time of failure */
    readonly slug?: string;
    /** Error message (truncated for safety) */
    readonly errorMessage: string;
    /** Elapsed milliseconds before failure */
    readonly elapsedMs: number;
}

// =============================================================================
// COST ESTIMATION
// =============================================================================

/**
 * Per-token pricing (USD) for Bedrock foundation models.
 *
 * Prices as of March 2026 for EU cross-region inference profiles.
 * Input/output costs are per 1,000 tokens.
 *
 * @see https://aws.amazon.com/bedrock/pricing/
 */
const MODEL_PRICING: Record<string, { inputPer1k: number; outputPer1k: number; thinkingPer1k: number }> = {
    'eu.anthropic.claude-sonnet-4-6-20260310-v1:0': {
        inputPer1k: 0.003,
        outputPer1k: 0.015,
        thinkingPer1k: 0.015,
    },
    'eu.anthropic.claude-haiku-3-5-20241022-v1:0': {
        inputPer1k: 0.0008,
        outputPer1k: 0.004,
        thinkingPer1k: 0.004,
    },
};

/** Fallback pricing if the model is not in the pricing table. */
const DEFAULT_PRICING = { inputPer1k: 0.003, outputPer1k: 0.015, thinkingPer1k: 0.015 };

/**
 * Estimate the USD cost of a single Bedrock invocation.
 *
 * @param model - Foundation model identifier
 * @param usage - Token usage breakdown
 * @returns Estimated cost in USD (rounded to 6 decimal places)
 */
export function estimateInvocationCost(model: string, usage: TokenUsage): number {
    const pricing = MODEL_PRICING[model] ?? DEFAULT_PRICING;
    const cost =
        (usage.inputTokens / 1000) * pricing.inputPer1k +
        (usage.outputTokens / 1000) * pricing.outputPer1k +
        (usage.thinkingTokens / 1000) * pricing.thinkingPer1k;
    return Math.round(cost * 1_000_000) / 1_000_000;
}

// =============================================================================
// STAGE TIMER
// =============================================================================

/**
 * High-resolution pipeline stage timer.
 *
 * Records start/end timestamps for each named pipeline stage and
 * produces a {@link StageDurations} object for EMF emission.
 *
 * @example
 * ```typescript
 * const timer = new StageTimer();
 * timer.start('readDraft');
 * const draft = await readDraftFromS3(bucket, key);
 * timer.end('readDraft');
 *
 * timer.start('bedrockConverse');
 * const result = await transformWithBedrock(msg, complexity);
 * timer.end('bedrockConverse');
 *
 * const durations = timer.getDurations();
 * // { totalMs: 12500, readDraftMs: 250, bedrockConverseMs: 12250 }
 * ```
 */
export class StageTimer {
    /** Pipeline-level start timestamp */
    private readonly pipelineStart: number;

    /** Per-stage start timestamps */
    private readonly starts = new Map<string, number>();

    /** Per-stage elapsed milliseconds */
    private readonly durations = new Map<string, number>();

    constructor() {
        this.pipelineStart = Date.now();
    }

    /**
     * Mark the start of a pipeline stage.
     *
     * @param stage - Stage name matching a key in {@link StageDurations}
     */
    public start(stage: string): void {
        this.starts.set(stage, Date.now());
    }

    /**
     * Mark the end of a pipeline stage and record its duration.
     *
     * @param stage - Stage name (must match a previous `start()` call)
     * @throws Error if `start()` was not called for this stage
     */
    public end(stage: string): void {
        const startTime = this.starts.get(stage);
        if (startTime === undefined) {
            throw new Error(`StageTimer: end('${stage}') called without matching start()`);
        }
        this.durations.set(stage, Date.now() - startTime);
    }

    /**
     * Get the total elapsed time since the timer was created.
     *
     * @returns Elapsed milliseconds
     */
    public elapsed(): number {
        return Date.now() - this.pipelineStart;
    }

    /**
     * Build a {@link StageDurations} object from all recorded stages.
     *
     * @returns Stage durations with `totalMs` always populated
     */
    public getDurations(): StageDurations {
        return {
            totalMs: this.elapsed(),
            readDraftMs: this.durations.get('readDraft'),
            kbRetrievalMs: this.durations.get('kbRetrieval'),
            bedrockConverseMs: this.durations.get('bedrockConverse'),
            parseResponseMs: this.durations.get('parseResponse'),
            qaValidationMs: this.durations.get('qaValidation'),
            s3WriteMs: this.durations.get('s3Write'),
            dynamoWriteMs: this.durations.get('dynamoWrite'),
        };
    }
}

// =============================================================================
// EMF EMISSION
// =============================================================================

/**
 * Emit CloudWatch custom metrics via EMF for a successful pipeline execution.
 *
 * Prints a structured JSON object to stdout that CloudWatch automatically
 * parses into metrics. Zero-latency, zero-SDK-overhead approach.
 *
 * Namespace: `BedrockPublisher`
 * Dimensions: `[Environment, Model]` for cost/performance slicing
 *
 * @param ctx - Complete pipeline execution context
 */
export function emitPipelineMetrics(ctx: PipelineMetricsContext): void {
    const estimatedCost = estimateInvocationCost(ctx.model, ctx.tokenUsage);

    /** Short model label for Grafana display (strip region prefix and version suffix) */
    const modelLabel = ctx.model
        .replace(/^eu\./, '')
        .replace(/anthropic\./, '')
        .replace(/-\d{8}-v\d+:\d+$/, '');

    const emfPayload: Record<string, unknown> = {
        _aws: {
            Timestamp: Date.now(),
            CloudWatchMetrics: [
                {
                    Namespace: 'BedrockPublisher',
                    Dimensions: [['Environment', 'Model']],
                    Metrics: [
                        { Name: 'ArticlesPublished', Unit: 'Count' },
                        { Name: 'InputTokens', Unit: 'Count' },
                        { Name: 'OutputTokens', Unit: 'Count' },
                        { Name: 'ThinkingTokens', Unit: 'Count' },
                        { Name: 'EstimatedCostUSD', Unit: 'None' },
                        { Name: 'ProcessingDurationMs', Unit: 'Milliseconds' },
                        { Name: 'DraftSizeBytes', Unit: 'Bytes' },
                        { Name: 'TechnicalConfidence', Unit: 'None' },
                    ],
                },
                {
                    Namespace: 'BedrockPublisher',
                    Dimensions: [['Environment', 'ComplexityTier']],
                    Metrics: [
                        { Name: 'ContentComplexity', Unit: 'Count' },
                    ],
                },
            ],
        },

        // Dimension values
        Environment: ctx.environment,
        Model: modelLabel,
        ComplexityTier: ctx.complexityTier,

        // Metric values
        ArticlesPublished: 1,
        InputTokens: ctx.tokenUsage.inputTokens,
        OutputTokens: ctx.tokenUsage.outputTokens,
        ThinkingTokens: ctx.tokenUsage.thinkingTokens,
        EstimatedCostUSD: estimatedCost,
        ProcessingDurationMs: ctx.stageDurations.totalMs,
        DraftSizeBytes: ctx.draftSizeBytes,
        TechnicalConfidence: ctx.technicalConfidence,
        ContentComplexity: 1,

        // High-cardinality fields (searchable in logs, NOT dimensions)
        Slug: ctx.slug,
        Mode: ctx.mode,
        BedrockConverseMs: ctx.stageDurations.bedrockConverseMs ?? 0,
        S3WriteMs: ctx.stageDurations.s3WriteMs ?? 0,
        DynamoWriteMs: ctx.stageDurations.dynamoWriteMs ?? 0,
    };

    // Append QA metrics if QA agent was invoked
    if (ctx.qaScore !== undefined) {
        emfPayload.QaScore = ctx.qaScore;
        emfPayload.QaDurationMs = ctx.qaDurationMs ?? 0;
    }

    console.log(JSON.stringify(emfPayload));
}

/**
 * Emit CloudWatch custom metrics for a pipeline failure.
 *
 * Tracks which stage failed and how long the pipeline ran before failure.
 *
 * @param ctx - Failure context with stage and error details
 */
export function emitFailureMetrics(ctx: FailureMetricsContext): void {
    /** Short model label for consistency */
    const modelLabel = ctx.model
        .replace(/^eu\./, '')
        .replace(/anthropic\./, '')
        .replace(/-\d{8}-v\d+:\d+$/, '');

    const emfPayload = {
        _aws: {
            Timestamp: Date.now(),
            CloudWatchMetrics: [
                {
                    Namespace: 'BedrockPublisher',
                    Dimensions: [['Environment', 'FailureStage']],
                    Metrics: [
                        { Name: 'ArticlesFailed', Unit: 'Count' },
                        { Name: 'FailureDurationMs', Unit: 'Milliseconds' },
                    ],
                },
            ],
        },

        // Dimension values
        Environment: ctx.environment,
        Model: modelLabel,
        FailureStage: ctx.failureStage,

        // Metric values
        ArticlesFailed: 1,
        FailureDurationMs: ctx.elapsedMs,

        // High-cardinality fields (logs only)
        Slug: ctx.slug ?? 'unknown',
        ErrorMessage: ctx.errorMessage.substring(0, 500),
    };

    console.log(JSON.stringify(emfPayload));
}
