/**
 * @fileoverview Generates Architecture Decision Records (ADRs).
 *
 * Each ADR documents a real decision made in the project, with evidence
 * files that prove the decision was implemented. No fabricated context —
 * only facts traceable to the repository.
 *
 * @module generators/adr-generator
 */

import type { AdrTopic } from '../types/index.js';

/**
 * Generates an Architecture Decision Record markdown document.
 *
 * @param topic - The ADR topic with evidence patterns.
 * @param evidenceFiles - Actual file paths matching the topic's evidence patterns.
 * @returns Markdown string for the ADR.
 */
export function generateAdr(
  topic: AdrTopic,
  evidenceFiles: readonly string[],
): string {
  const lines: string[] = [];
  const date = new Date().toISOString().split('T')[0];

  lines.push(`# ADR: ${topic.title}`);
  lines.push('');
  lines.push(`**Date:** ${date}`);
  lines.push('');
  lines.push('**Status:** Accepted');
  lines.push('');

  // Context
  lines.push('## Context');
  lines.push('');
  lines.push(topic.context);
  lines.push('');

  // Evidence
  lines.push('## Evidence');
  lines.push('');
  lines.push('> Files in this repository that demonstrate this decision:');
  lines.push('');
  if (evidenceFiles.length > 0) {
    for (const file of evidenceFiles.slice(0, 10)) {
      lines.push(`- \`${file}\``);
    }
    if (evidenceFiles.length > 10) {
      lines.push(`- *(+${evidenceFiles.length - 10} additional files)*`);
    }
  } else {
    lines.push('- *No matching evidence files found. Review the evidence patterns for this decision.*');
  }
  lines.push('');

  // Decision
  lines.push('## Decision');
  lines.push('');
  lines.push('<!-- Describe the specific decision and reasoning in first-person:');
  lines.push('     "I chose X because..." -->');
  lines.push('');

  // Consequences
  lines.push('## Consequences');
  lines.push('');
  lines.push('### Benefits');
  lines.push('');
  lines.push('<!-- What I gained from this decision. Be specific and measurable. -->');
  lines.push('');
  lines.push('### Trade-offs');
  lines.push('');
  lines.push('<!-- What I gave up or what additional burden this creates. -->');
  lines.push('');

  lines.push('---');
  lines.push('');
  lines.push('*Generated by mcp-portfolio-docs — evidence files listed above are real paths in this repository.*');

  return lines.join('\n');
}
