/**
 * @fileoverview Generates chaos test evidence templates.
 *
 * Provides a structured document for recording chaos experiments,
 * with placeholders for screenshots, recovery details, and
 * links to Step Functions execution graphs.
 *
 * @module generators/chaos-evidence-generator
 */

import type { DetectedSkill } from '../types/index.js';

/**
 * Generates a chaos test evidence template markdown document.
 *
 * @param detectedSkills - Skills related to resilience/self-healing.
 * @returns Markdown string for the chaos test evidence document.
 */
export function generateChaosEvidence(
  detectedSkills: readonly DetectedSkill[],
): string {
  const lines: string[] = [];
  const date = new Date().toISOString().split('T')[0];

  lines.push('# Chaos Test Evidence');
  lines.push('');
  lines.push(`**Date:** ${date}`);
  lines.push('');
  lines.push('> Document the results of chaos experiments against this infrastructure.');
  lines.push('> Fill in each section after performing the experiment.');
  lines.push('');

  // Related infrastructure
  const resilienceSkills = detectedSkills.filter((s) =>
    ['step-functions', 'kubernetes-selfmanaged', 'argocd', 'helm', 'prometheus'].includes(s.skillId),
  );

  if (resilienceSkills.length > 0) {
    lines.push('## Related Infrastructure');
    lines.push('');
    lines.push('| Component | Evidence |');
    lines.push('| :--- | :--- |');
    for (const skill of resilienceSkills) {
      const evidence = skill.evidence.slice(0, 2).map((e) => `\`${e}\``).join(', ');
      lines.push(`| ${skill.skillName} | ${evidence} |`);
    }
    lines.push('');
  }

  // Experiment template
  lines.push('## Experiment: Instance Termination');
  lines.push('');
  lines.push('### Hypothesis');
  lines.push('');
  lines.push('When the EC2 worker node is terminated, the Step Functions self-healing pipeline');
  lines.push('should detect the failure, launch a replacement, and rejoin the Kubernetes cluster.');
  lines.push('');

  lines.push('### Method');
  lines.push('');
  lines.push('1. Record the current node state: `kubectl get nodes`');
  lines.push('2. Terminate the EC2 instance via AWS Console or CLI');
  lines.push('3. Monitor the Step Functions execution graph');
  lines.push('4. Wait for the replacement node to join the cluster');
  lines.push('5. Verify all pods rescheduled: `kubectl get pods -A`');
  lines.push('');

  lines.push('### Results');
  lines.push('');
  lines.push('| Metric | Value |');
  lines.push('| :--- | :--- |');
  lines.push('| **Time to Detection** | <!-- e.g. 45 seconds --> |');
  lines.push('| **Time to Recovery** | <!-- e.g. 4 minutes 30 seconds --> |');
  lines.push('| **Pods Rescheduled** | <!-- e.g. 12/12 --> |');
  lines.push('| **Data Loss** | <!-- None / Describe --> |');
  lines.push('');

  lines.push('### Evidence Screenshots');
  lines.push('');
  lines.push('<!-- IMAGE: Step Functions execution graph showing recovery -->');
  lines.push('<!-- IMAGE: kubectl get nodes showing new node joined -->');
  lines.push('<!-- IMAGE: Grafana dashboard showing recovery metrics -->');
  lines.push('');

  // Additional experiment template
  lines.push('## Experiment: Pod Disruption');
  lines.push('');
  lines.push('### Hypothesis');
  lines.push('');
  lines.push('When pods are evicted (simulating a drain), PodDisruptionBudgets should');
  lines.push('maintain service availability during the disruption window.');
  lines.push('');

  lines.push('### Method');
  lines.push('');
  lines.push('1. Record running pods: `kubectl get pods -n <namespace>`');
  lines.push('2. Drain the node: `kubectl drain <node> --ignore-daemonsets --delete-emptydir-data`');
  lines.push('3. Monitor pod rescheduling');
  lines.push('4. Uncordon: `kubectl uncordon <node>`');
  lines.push('');

  lines.push('### Results');
  lines.push('');
  lines.push('| Metric | Value |');
  lines.push('| :--- | :--- |');
  lines.push('| **Service Downtime** | <!-- e.g. 0 seconds --> |');
  lines.push('| **PDB Respected** | <!-- Yes / No --> |');
  lines.push('| **Pods Rescheduled** | <!-- e.g. 4/4 --> |');
  lines.push('');

  lines.push('---');
  lines.push('');
  lines.push('*Template generated by mcp-portfolio-docs — fill in results after performing experiments.*');

  return lines.join('\n');
}
