/**
 * @fileoverview Code-quality report generator.
 *
 * Transforms a {@link CodeQualityReport} into a structured markdown document
 * with summary scores, findings breakdown, top offenders, and recommendations.
 *
 * @module generators/code-quality-report
 */

import type { CodeQualityReport, FindingSeverity } from '../types/index.js';

/** Emoji badges for severity levels. */
const SEVERITY_BADGE: Record<FindingSeverity, string> = {
  error: '🔴',
  warning: '🟡',
  info: '🔵',
};

/**
 * Generates a structured markdown report from a code-quality scan.
 *
 * @param report - The aggregated code-quality report.
 * @returns Markdown string with summary, breakdown, top issues, and recommendations.
 */
export function generateCodeQualityReport(
  report: CodeQualityReport,
): string {
  const lines: string[] = [];
  const timestamp = new Date().toISOString();

  // Header
  lines.push(`<!-- Last updated: ${timestamp} -->`);
  lines.push('');
  lines.push('# Code Quality Report — TypeScript Hygiene & Standards');
  lines.push('');

  // Summary
  lines.push('## Summary');
  lines.push('');
  lines.push(`| Metric | Value |`);
  lines.push(`| :--- | :--- |`);
  lines.push(`| **Quality Score** | ${scoreEmoji(report.score)} **${report.score}/100** |`);
  lines.push(`| Files Scanned | ${report.totalFiles} |`);
  lines.push(`| Total Findings | ${report.totalFindings} |`);
  lines.push(`| Errors | ${countBySeverity(report, 'error')} |`);
  lines.push(`| Warnings | ${countBySeverity(report, 'warning')} |`);
  lines.push(`| Info | ${countBySeverity(report, 'info')} |`);
  lines.push('');

  // Findings by Rule
  lines.push('## Findings by Rule');
  lines.push('');
  if (Object.keys(report.findingsByRule).length > 0) {
    lines.push('| Rule | Count | Description |');
    lines.push('| :--- | ---: | :--- |');
    for (const [rule, count] of Object.entries(report.findingsByRule).sort(
      ([, a], [, b]) => b - a,
    )) {
      lines.push(`| \`${rule}\` | ${count} | ${ruleDescription(rule)} |`);
    }
  } else {
    lines.push('> ✅ No findings detected — excellent code hygiene!');
  }
  lines.push('');

  // Top Issues (limit to 20 worst)
  const topIssues = report.findings
    .filter((f) => f.severity === 'error' || f.severity === 'warning')
    .slice(0, 20);

  if (topIssues.length > 0) {
    lines.push('## Top Issues');
    lines.push('');
    lines.push('| Severity | File | Line | Rule | Message |');
    lines.push('| :---: | :--- | ---: | :--- | :--- |');
    for (const finding of topIssues) {
      lines.push(
        `| ${SEVERITY_BADGE[finding.severity]} | \`${finding.file}\` | ${finding.line} | \`${finding.rule}\` | ${finding.message} |`,
      );
    }
    lines.push('');
  }

  // Recommendations
  lines.push('## Recommendations');
  lines.push('');
  const recommendations = generateRecommendations(report);
  for (const rec of recommendations) {
    lines.push(`- ${rec}`);
  }
  lines.push('');

  lines.push('---');
  lines.push('');
  lines.push('*Generated by mcp-portfolio-docs `code-quality` scope — evidence-only, no fabricated claims.*');

  return lines.join('\n');
}

/**
 * Returns an emoji indicator for the quality score.
 *
 * @param score - Quality score (0–100).
 * @returns Emoji string.
 */
function scoreEmoji(score: number): string {
  if (score >= 90) return '🟢';
  if (score >= 70) return '🟡';
  if (score >= 50) return '🟠';
  return '🔴';
}

/**
 * Counts findings by severity.
 *
 * @param report - The code-quality report.
 * @param severity - Severity to count.
 * @returns Count of findings with that severity.
 */
function countBySeverity(
  report: CodeQualityReport,
  severity: FindingSeverity,
): number {
  return report.findings.filter((f) => f.severity === severity).length;
}

/**
 * Returns a human-readable description for a rule identifier.
 *
 * @param rule - Rule identifier string.
 * @returns Description of what the rule checks.
 */
function ruleDescription(rule: string): string {
  const descriptions: Record<string, string> = {
    'missing-jsdoc': 'Exported members lacking JSDoc/TSDoc documentation',
    'any-usage': 'Usage of `any` type — use `unknown` or specific types',
    'missing-import-type': 'Value import used where `import type` should be used',
    'magic-number': 'Magic numbers in logic — extract to named constants',
    'dry-violation': 'Duplicated code blocks across files',
  };
  return descriptions[rule] ?? 'Unrecognised rule';
}

/**
 * Generates actionable recommendations based on the report findings.
 *
 * @param report - The code-quality report.
 * @returns Array of recommendation strings.
 */
function generateRecommendations(report: CodeQualityReport): string[] {
  const recommendations: string[] = [];

  if ((report.findingsByRule['any-usage'] ?? 0) > 0) {
    recommendations.push(
      '**Eliminate `any` usage:** Replace all `any` types with `unknown` or specific interfaces. Enable `noImplicitAny` in `tsconfig.json`.',
    );
  }

  if ((report.findingsByRule['missing-jsdoc'] ?? 0) > 0) {
    recommendations.push(
      '**Improve JSDoc coverage:** Add TSDoc comments to all exported functions, classes, and interfaces. Consider using `eslint-plugin-jsdoc`.',
    );
  }

  if ((report.findingsByRule['missing-import-type'] ?? 0) > 0) {
    recommendations.push(
      '**Use `import type` for type-only imports:** Enable `@typescript-eslint/consistent-type-imports` rule in ESLint.',
    );
  }

  if ((report.findingsByRule['magic-number'] ?? 0) > 0) {
    recommendations.push(
      '**Extract magic numbers:** Define named constants at the top of each file or in a shared constants module.',
    );
  }

  if ((report.findingsByRule['dry-violation'] ?? 0) > 0) {
    recommendations.push(
      '**Reduce code duplication:** Extract shared logic into utility functions or base classes. Consider a shared `utils/` module.',
    );
  }

  if (recommendations.length === 0) {
    recommendations.push('No issues detected — maintain current standards and keep coding! 🚀');
  }

  return recommendations;
}
