/**
 * @fileoverview Generates scoped feature articles following AG-DOC-01 template.
 *
 * Produces markdown draft suitable for the Bedrock content pipeline
 * (blog-persona.ts). Includes editorial notes, Mermaid placeholders,
 * and decision log sections.
 *
 * @module generators/feature-article
 */

import type { CoverageMatrix, DetectedSkill, ScopeProfile } from '../types/index.js';

/**
 * Generates a feature article markdown for a scoped implementation area.
 *
 * @param scope - The scope profile used for scanning.
 * @param detectedSkills - Skills detected within the scope.
 * @param coverage - Coverage matrix for focus categories.
 * @returns Markdown string following AG-DOC-01 template.
 */
export function generateFeatureArticle(
  scope: ScopeProfile,
  detectedSkills: readonly DetectedSkill[],
  coverage: CoverageMatrix,
): string {
  const lines: string[] = [];

  // Editorial hints for the Bedrock pipeline
  lines.push('<!-- EDITORIAL NOTES FOR THE PRINCIPAL EDITOR');
  lines.push(`- Preferred Title: "Building ${scope.name} — A Solo DevOps Implementation"`);
  lines.push(`- Include a "Junior Corner" callout explaining ${scope.id} for readers who are new to the domain.`);
  lines.push('- Emphasise the "WHY" behind every technical decision.');
  lines.push('- Ensure first-person singular voice throughout.');
  lines.push('-->');
  lines.push('');

  // Title
  lines.push(`# ${scope.name}`);
  lines.push('');

  // Executive summary
  lines.push('## Executive Summary');
  lines.push('');
  lines.push(`This implementation covers **${detectedSkills.length}** skills across **${coverage.categories.filter((c) => c.demonstrated.length > 0).length}** categories.`);
  lines.push('');
  lines.push('### Skills Demonstrated');
  lines.push('');
  for (const skill of detectedSkills) {
    lines.push(`- **${skill.skillName}** (${skill.demand} demand) — Evidence: ${skill.evidence.slice(0, 2).map((e) => `\`${e}\``).join(', ')}`);
  }
  lines.push('');

  // Architecture overview (template — AI editor fills detail)
  lines.push('## Architecture Overview');
  lines.push('');
  lines.push('<!-- IMAGE: Architecture diagram for this implementation -->');
  lines.push('');
  lines.push('```mermaid');
  lines.push('graph LR');
  lines.push(`    A["${scope.name}"] --> B["Implementation Detail"]`);
  lines.push(`    style A fill:#2d6a4f,color:#fff`);
  lines.push('```');
  lines.push('');

  // Evidence inventory
  lines.push('## Implementation Evidence');
  lines.push('');
  lines.push('| Skill | Evidence Files |');
  lines.push('| :--- | :--- |');
  for (const skill of detectedSkills) {
    const evidenceStr = skill.evidence
      .slice(0, 3)
      .map((e) => `\`${e}\``)
      .join(', ');
    lines.push(`| ${skill.skillName} | ${evidenceStr} |`);
  }
  lines.push('');

  // Decision log placeholder
  lines.push('## Decision Log');
  lines.push('');
  lines.push('> Document the key "WHY X over Y" trade-offs for this implementation.');
  lines.push('> See `docs/adrs/` for formal Architecture Decision Records.');
  lines.push('');

  // Lessons learned placeholder
  lines.push('## Lessons Learned');
  lines.push('');
  lines.push('<!-- Fill in 3-4 bullet points (never exactly 5). Vary grammatical structure. -->');
  lines.push('');

  lines.push('---');
  lines.push('');
  lines.push('*Generated by mcp-portfolio-docs — evidence-only, no fabricated claims.*');

  return lines.join('\n');
}
