/**
 * @fileoverview Generates the portfolio overview markdown document.
 *
 * This is the output of a full repo scan — a high-level summary of
 * all demonstrated skills, market coverage, and evidence references.
 *
 * @module generators/portfolio-overview
 */

import type { CoverageMatrix, DetectedSkill } from '../types/index.js';

/**
 * Renders a demand level as a visual badge.
 *
 * @param demand - The demand level string.
 * @returns Emoji badge for the demand level.
 */
function demandBadge(demand: string): string {
  switch (demand) {
    case 'high':
      return '🔴 High';
    case 'medium-high':
      return '🟠 Medium-High';
    case 'medium':
      return '🟡 Medium';
    case 'low':
      return '⚪ Low';
    default:
      return demand;
  }
}

/**
 * Renders the evidence list for a detected skill (max 3 files).
 *
 * @param evidence - Array of relative file paths.
 * @returns Markdown-formatted evidence string.
 */
function renderEvidence(evidence: readonly string[]): string {
  const shown = evidence.slice(0, 3);
  const suffix = evidence.length > 3 ? ` (+${evidence.length - 3} more)` : '';
  return shown.map((f) => `\`${f}\``).join(', ') + suffix;
}

/**
 * Generates the full portfolio overview markdown.
 *
 * @param coverage - Coverage matrix from market matcher.
 * @param detectedSkills - All skills detected with evidence.
 * @returns Markdown string for the portfolio overview document.
 */
export function generatePortfolioOverview(
  coverage: CoverageMatrix,
  detectedSkills: readonly DetectedSkill[],
): string {
  const lines: string[] = [];

  lines.push('# Portfolio Skills Overview');
  lines.push('');
  lines.push('> Auto-generated by `mcp-portfolio-docs`. Every claim is backed by evidence from the repository.');
  lines.push('');

  // Executive summary
  lines.push('## Summary');
  lines.push('');
  lines.push(`| Metric | Value |`);
  lines.push(`| :--- | :--- |`);
  lines.push(`| **Skills Demonstrated** | ${coverage.totalDemonstrated} / ${coverage.totalInTaxonomy} |`);
  lines.push(`| **Overall Coverage** | ${coverage.overallCoveragePercent}% |`);
  lines.push(`| **Categories Covered** | ${coverage.categories.filter((c) => c.coveragePercent > 0).length} / ${coverage.categories.length} |`);
  lines.push('');

  // Coverage matrix
  lines.push('## Coverage Matrix');
  lines.push('');
  lines.push('| Category | Coverage | Demonstrated | Total |');
  lines.push('| :--- | :--- | :--- | :--- |');

  for (const cat of coverage.categories) {
    const bar = cat.coveragePercent >= 75 ? '🟢' : cat.coveragePercent >= 50 ? '🟡' : '🔴';
    lines.push(
      `| ${cat.categoryName} | ${bar} ${cat.coveragePercent}% | ${cat.demonstrated.length} | ${cat.demonstrated.length + cat.notDemonstrated.length} |`,
    );
  }
  lines.push('');

  // Detailed skills per category
  lines.push('## Demonstrated Skills');
  lines.push('');

  for (const cat of coverage.categories) {
    if (cat.demonstrated.length === 0) continue;

    lines.push(`### ${cat.categoryName}`);
    lines.push('');
    lines.push('| Skill | Market Demand | Evidence |');
    lines.push('| :--- | :--- | :--- |');

    for (const skill of cat.demonstrated) {
      lines.push(`| ${skill.skillName} | ${demandBadge(skill.demand)} | ${renderEvidence(skill.evidence)} |`);
    }
    lines.push('');
  }

  // Gaps
  const allGaps = coverage.categories.flatMap((cat) =>
    cat.notDemonstrated.map((skill) => ({
      category: cat.categoryName,
      skill: skill.name,
      demand: skill.demand,
    })),
  );

  if (allGaps.length > 0) {
    lines.push('## Growth Opportunities');
    lines.push('');
    lines.push('> Skills in the market taxonomy not yet demonstrated in this repository.');
    lines.push('');
    lines.push('| Category | Skill | Market Demand |');
    lines.push('| :--- | :--- | :--- |');

    const highDemandGaps = allGaps.filter((g) => g.demand === 'high' || g.demand === 'medium-high');
    for (const gap of highDemandGaps) {
      lines.push(`| ${gap.category} | ${gap.skill} | ${demandBadge(gap.demand)} |`);
    }
    lines.push('');
  }

  // High-demand highlights
  const highDemandSkills = detectedSkills.filter((s) => s.demand === 'high');
  if (highDemandSkills.length > 0) {
    lines.push('## High-Demand Skills Signal');
    lines.push('');
    lines.push(`This portfolio demonstrates **${highDemandSkills.length}** skills classified as **high demand** in DevOps/Cloud Engineering roles:`);
    lines.push('');
    for (const skill of highDemandSkills) {
      lines.push(`- **${skill.skillName}** — ${renderEvidence(skill.evidence)}`);
    }
    lines.push('');
  }

  lines.push('---');
  lines.push('');
  lines.push('*Generated by mcp-portfolio-docs — evidence-only, no fabricated claims.*');

  return lines.join('\n');
}
