helm:
  parameters:
  - name: image.tag
    value: c9614a118d2e17473545f49c79bed92f3497854b-r1
    forcestring: true
  - name: image.repository
    value: 771826808455.dkr.ecr.eu-west-1.amazonaws.com/start-admin
    forcestring: true
