helm:
  parameters:
  - name: image.tag
    value: 5f7bf6ea98f3c97d52fcf4abd255b819b400af78-r1
    forcestring: true
  - name: image.repository
    value: 771826808455.dkr.ecr.eu-west-1.amazonaws.com/nextjs-frontend
    forcestring: true
