helm:
  parameters:
  - name: image.tag
    value: 1ff23bb75d8e2ef382922c9fbda1eacc9dbcdd0a
    forcestring: true
  - name: image.repository
    value: 771826808455.dkr.ecr.eu-west-1.amazonaws.com/nextjs-frontend
    forcestring: true
