# @format

name: "Deploy CDK Stack"
description: "Simplified CDK stack deployment with inline validation and flexible context"

inputs:
  stack-name:
    description: "Name of the CDK stack to deploy (should contain project context)"
    required: true
  project:
    description: "Project name (monitoring, nextjs, org)"
    required: true
  environment:
    description: "Target environment (development, staging, production)"
    required: true
  aws-account-id:
    description: "Target AWS Account ID"
    required: true
  aws-region:
    description: "AWS Region"
    required: true
  additional-args:
    description: "Additional CDK deploy arguments (excluding --require-approval)"
    required: false
    default: ""
  require-approval:
    description: "CDK approval requirement (never, any-change, broadening)"
    required: false
    default: "never"
  verify-bootstrap:
    description: "Verify CDK bootstrap before deployment"
    required: false
    default: "false"
  outputs-directory:
    description: "Directory to save stack outputs (optional)"
    required: false
    default: ""

outputs:
  deployment-status:
    description: "Status of deployment (success/failure)"
    value: ${{ steps.deploy.outputs.status }}
  stack-outputs:
    description: "CloudFormation stack outputs (JSON)"
    value: ${{ steps.outputs.outputs.stack_outputs }}
  outputs-file:
    description: "Path to saved outputs file (if outputs-directory specified)"
    value: ${{ steps.outputs.outputs.file_path }}

runs:
  using: "composite"
  steps:
    - name: Pre-flight Checks
      shell: bash
      run: |
        BOOTSTRAP_FLAG=""
        if [ "${{ inputs.verify-bootstrap }}" = "true" ]; then
          BOOTSTRAP_FLAG="--verify-bootstrap"
        fi
        just ci-preflight "${{ inputs.stack-name }}" \
          --project "${{ inputs.project }}" \
          --environment "${{ inputs.environment }}" \
          --region "${{ inputs.aws-region }}" \
          --account-id "${{ inputs.aws-account-id }}" \
          --require-approval "${{ inputs.require-approval }}" \
          $BOOTSTRAP_FLAG
      env:
        AWS_REGION: ${{ inputs.aws-region }}

    - name: Deploy Stack
      id: deploy
      shell: bash
      run: |
        just ci-deploy "${{ inputs.stack-name }}" "${{ inputs.project }}" "${{ inputs.environment }}" \
          --require-approval "${{ inputs.require-approval }}" \
          ${{ inputs.additional-args }}
      env:
        CDK_ENVIRONMENT: ${{ inputs.environment }}
        AWS_ACCOUNT_ID: ${{ inputs.aws-account-id }}
        AWS_REGION: ${{ inputs.aws-region }}

    - name: Diagnose CloudFormation Failure
      if: failure() && steps.deploy.outputs.status != 'success'
      shell: bash
      continue-on-error: true
      run: |
        just ci-diagnose "${{ inputs.stack-name }}" --region "${{ inputs.aws-region }}"
      env:
        AWS_REGION: ${{ inputs.aws-region }}

    - name: Collect Stack Outputs
      id: outputs
      if: always()
      shell: bash
      run: |
        just ci-collect-outputs "${{ inputs.stack-name }}" \
          --deploy-status "${{ steps.deploy.outputs.status }}" \
          --outputs-dir "${{ inputs.outputs-directory }}"
      env:
        GITHUB_WORKSPACE: ${{ github.workspace }}

    - name: Generate Deployment Summary
      if: always()
      shell: bash
      run: |
        just ci-deploy-summary "${{ inputs.stack-name }}" \
          --environment "${{ inputs.environment }}" \
          --region "${{ inputs.aws-region }}" \
          --account-id "${{ inputs.aws-account-id }}" \
          --deploy-status "${{ steps.deploy.outputs.status }}" \
          --deploy-duration "${{ steps.deploy.outputs.duration }}" \
          --outputs-file "${{ steps.outputs.outputs.file_path }}"
