/**
 * @fileoverview Generates solo-operator runbook documents.
 *
 * Runbooks are framed for a single developer operating own infrastructure.
 * No escalation paths, no team handoffs — just trigger, automatic response,
 * manual verification, and recovery evidence.
 *
 * @module generators/runbook-generator
 */

import type { RunbookScenario } from '../types/index.js';

/**
 * Generates a runbook markdown document.
 *
 * @param scenario - The runbook scenario template.
 * @param autoResponseFiles - Evidence files for automatic response mechanisms.
 * @param recoveryFiles - Evidence files for recovery monitoring.
 * @returns Markdown string for the runbook.
 */
export function generateRunbook(
  scenario: RunbookScenario,
  autoResponseFiles: readonly string[],
  recoveryFiles: readonly string[],
): string {
  const lines: string[] = [];
  const date = new Date().toISOString().split('T')[0];

  lines.push(`# Runbook: ${scenario.title}`);
  lines.push('');
  lines.push(`**Last Updated:** ${date}`);
  lines.push('');
  lines.push('**Operator:** Solo — infrastructure owner');
  lines.push('');

  // Trigger
  lines.push('## Trigger');
  lines.push('');
  lines.push(scenario.trigger);
  lines.push('');

  // Automatic response
  lines.push('## Automatic Response');
  lines.push('');
  lines.push('> Infrastructure mechanisms that respond to this scenario without manual intervention.');
  lines.push('');
  if (autoResponseFiles.length > 0) {
    lines.push('### Evidence Files');
    lines.push('');
    for (const file of autoResponseFiles.slice(0, 8)) {
      lines.push(`- \`${file}\``);
    }
    lines.push('');
  }
  lines.push('<!-- Describe what happens automatically when this trigger fires. -->');
  lines.push('');

  // Manual verification
  lines.push('## Manual Verification');
  lines.push('');
  lines.push('After the automatic response, verify:');
  lines.push('');
  for (const [idx, check] of scenario.manualChecks.entries()) {
    lines.push(`${idx + 1}. ${check}`);
  }
  lines.push('');

  // Recovery evidence
  lines.push('## Recovery Evidence');
  lines.push('');
  lines.push('> Where to confirm the system has recovered:');
  lines.push('');
  if (recoveryFiles.length > 0) {
    for (const file of recoveryFiles.slice(0, 6)) {
      lines.push(`- \`${file}\``);
    }
  }
  lines.push('');
  lines.push('<!-- Add screenshots of dashboards showing recovery. -->');
  lines.push('');

  // Postmortem template
  lines.push('## Postmortem Notes');
  lines.push('');
  lines.push('| Field | Value |');
  lines.push('| :--- | :--- |');
  lines.push('| **Incident Date** | |');
  lines.push('| **Detection Time** | |');
  lines.push('| **Recovery Time** | |');
  lines.push('| **Root Cause** | |');
  lines.push('| **Action Taken** | |');
  lines.push('');

  lines.push('---');
  lines.push('');
  lines.push('*Generated by mcp-portfolio-docs — evidence files are real paths in this repository.*');

  return lines.join('\n');
}
