/**
 * @format
 * Kubernetes Observability Stack — Pre-Deployment CloudWatch Dashboard
 *
 * Lightweight stack providing infrastructure observability before
 * Grafana/Prometheus are operational. All resource references are
 * resolved via SSM parameters — fully decoupled from compute lifecycle.
 *
 * Resources Created:
 *   - CloudWatch Dashboard (7 metric sections)
 *
 * Cost: $3.00/month (dashboard resource only).
 *
 * Deployment:
 *   Depends on Base stack (SSM parameters must exist).
 *   Can be deployed/updated independently of compute stacks.
 *
 * @example
 * ```typescript
 * const observabilityStack = new KubernetesObservabilityStack(app, 'Observability-dev', {
 *     env: cdkEnvironment(Environment.DEVELOPMENT),
 *     targetEnvironment: Environment.DEVELOPMENT,
 *     namePrefix: 'k8s-dev',
 *     ssmPrefix: '/k8s/development',
 * });
 * ```
 */

import * as ssm from 'aws-cdk-lib/aws-ssm';
import * as cdk from 'aws-cdk-lib/core';

import { Construct } from 'constructs';

import { Environment } from '../../config/environments';
import {
    InfrastructureDashboard,
    OperationsDashboard,
} from '../../constructs/observability';
import type {
    DashboardLambdaConfig,
    OpsDashboardSelfHealingConfig,
} from '../../constructs/observability';

// =============================================================================
// PROPS
// =============================================================================

/**
 * Props for {@link KubernetesObservabilityStack}.
 */
export interface KubernetesObservabilityStackProps extends cdk.StackProps {
    /** Target deployment environment */
    readonly targetEnvironment: Environment;

    /** Resource name prefix (e.g. `k8s-dev`) */
    readonly namePrefix: string;

    /** SSM parameter prefix for the Kubernetes cluster @example '/k8s/development' */
    readonly ssmPrefix: string;

    /**
     * CloudFront distribution ID for CDN metrics.
     * Resolved from SSM at synth time by the factory.
     * Omit to skip CloudFront section.
     */
    readonly cloudFrontDistributionId?: string;

    /**
     * Step Functions state machine name for bootstrap orchestrator metrics.
     * Omit to skip Step Functions section.
     */
    readonly stateMachineName?: string;

    /**
     * Lambda function names to monitor.
     * Omit to skip Lambda section.
     */
    readonly lambdaFunctions?: DashboardLambdaConfig[];

    /**
     * NLB full name for CloudWatch metrics.
     * Format: `net/{lb-name}/{lb-id}`
     *
     * NOTE: The NLB full name contains a random suffix generated by AWS
     * at creation time, which is not available at CDK synth time.
     * Pass this value via SSM or leave undefined to use the NLB name only.
     */
    readonly nlbFullName?: string;

    /**
     * Self-healing pipeline Lambda configuration.
     * When provided, the Operations Dashboard includes agent + tool metrics.
     */
    readonly selfHealingConfig?: OpsDashboardSelfHealingConfig;
}

// =============================================================================
// STACK
// =============================================================================

/**
 * Kubernetes Observability Stack — Pre-deployment CloudWatch dashboard.
 *
 * Reads infrastructure references from SSM and creates a CloudWatch
 * dashboard covering EC2, NLB, Step Functions, Lambda, and CloudFront.
 */
export class KubernetesObservabilityStack extends cdk.Stack {
    /** The infrastructure dashboard construct */
    public readonly dashboard: InfrastructureDashboard;

    constructor(scope: Construct, id: string, props: KubernetesObservabilityStackProps) {
        super(scope, id, {
            ...props,
            description: `Pre-deployment CloudWatch dashboard for K8s infrastructure - ${props.targetEnvironment}`,
        });

        const { namePrefix, ssmPrefix } = props;

        // =================================================================
        // Resolve ASG names from naming convention
        //
        // ASG names follow the pattern: {namePrefix}-{role}
        // These are set by AutoScalingGroupConstruct via the instanceName prop.
        // =================================================================
        const controlPlaneAsgName = `${namePrefix}-control-plane`;
        const appWorkerAsgName = `${namePrefix}-app-worker`;
        const monitoringWorkerAsgName = `${namePrefix}-mon-worker`;

        // =================================================================
        // Resolve NLB name from naming convention
        //
        // NLB name is set in base-stack.ts: `${namePrefix}-nlb`
        // CloudWatch NLB metrics require the full name format: net/{name}/{id}
        // If nlbFullName is not provided, we use just the NLB name —
        // the dashboard will show metrics once the NLB exists.
        // =================================================================
        const nlbName = props.nlbFullName ?? `net/${namePrefix}-nlb/placeholder`;

        // =================================================================
        // Read EBS volume ID from SSM (for future EBS widgets)
        // =================================================================
        const _ebsVolumeId = ssm.StringParameter.valueForStringParameter(
            this, `${ssmPrefix}/ebs-volume-id`,
        );

        // =================================================================
        // Dashboard Construct
        // =================================================================
        this.dashboard = new InfrastructureDashboard(this, 'InfraDashboard', {
            namePrefix,
            region: this.region,
            ec2: {
                controlPlaneAsgName,
                appWorkerAsgName,
                monitoringWorkerAsgName,
            },
            nlb: {
                loadBalancerFullName: nlbName,
            },
            stateMachine: props.stateMachineName
                ? { name: props.stateMachineName }
                : undefined,
            lambdaFunctions: props.lambdaFunctions,
            cloudFront: props.cloudFrontDistributionId
                ? { distributionId: props.cloudFrontDistributionId }
                : undefined,
        });

        // =================================================================
        // Stack Outputs
        // =================================================================
        new cdk.CfnOutput(this, 'DashboardName', {
            value: this.dashboard.dashboardName,
            description: 'CloudWatch Dashboard name',
        });

        new cdk.CfnOutput(this, 'DashboardUrl', {
            value: `https://${this.region}.console.aws.amazon.com/cloudwatch/home?region=${this.region}#dashboards:name=${this.dashboard.dashboardName}`,
            description: 'Direct link to the Infrastructure Dashboard',
        });

        // =================================================================
        // Operations Dashboard — Deployment Execution Traceability
        //
        // Separate dashboard for runtime visibility: AMI builds, SSM
        // bootstrap, drift enforcement, and self-healing pipeline.
        // =================================================================
        const opsDashboard = new OperationsDashboard(this, 'OpsDashboard', {
            namePrefix,
            region: this.region,
            ssmPrefix,
            selfHealing: props.selfHealingConfig,
        });

        new cdk.CfnOutput(this, 'OpsDashboardName', {
            value: opsDashboard.dashboardName,
            description: 'CloudWatch Operations Dashboard name',
        });

        new cdk.CfnOutput(this, 'OpsDashboardUrl', {
            value: `https://${this.region}.console.aws.amazon.com/cloudwatch/home?region=${this.region}#dashboards:name=${opsDashboard.dashboardName}`,
            description: 'Direct link to the Operations Dashboard',
        });
    }
}
