/**
 * @format
 * Kubernetes Observability Stack — Pre-Deployment CloudWatch Dashboard
 *
 * Lightweight stack providing infrastructure observability before
 * Grafana/Prometheus are operational. All resource references are
 * resolved via SSM parameters — fully decoupled from compute lifecycle.
 *
 * Resources Created:
 *   - CloudWatch Dashboard (7 metric sections)
 *
 * Cost: $3.00/month (dashboard resource only).
 *
 * Deployment:
 *   Depends on Base stack (SSM parameters must exist).
 *   Can be deployed/updated independently of compute stacks.
 *
 * @example
 * ```typescript
 * const observabilityStack = new KubernetesObservabilityStack(app, 'Observability-dev', {
 *     env: cdkEnvironment(Environment.DEVELOPMENT),
 *     targetEnvironment: Environment.DEVELOPMENT,
 *     namePrefix: 'k8s-dev',
 *     ssmPrefix: '/k8s/development',
 * });
 * ```
 */


import * as ssm from 'aws-cdk-lib/aws-ssm';
import * as cdk from 'aws-cdk-lib/core';

import { Construct } from 'constructs';

import { Environment } from '../../config/environments';
import {
    InfrastructureDashboard,
    OperationsDashboard,
} from '../../constructs/observability';
import type {
    OpsDashboardSelfHealingConfig,
} from '../../constructs/observability';

// =============================================================================
// PROPS
// =============================================================================

/**
 * Props for {@link KubernetesObservabilityStack}.
 */
export interface KubernetesObservabilityStackProps extends cdk.StackProps {
    /** Target deployment environment */
    readonly targetEnvironment: Environment;

    /** Resource name prefix (e.g. `k8s-dev`) */
    readonly namePrefix: string;

    /** SSM parameter prefix for the Kubernetes cluster @example '/k8s/development' */
    readonly ssmPrefix: string;

    /**
     * SSM path containing the CloudFront distribution ID.
     * Resolved at deploy time via `ssm.StringParameter.valueForStringParameter`.
     * Omit to skip CloudFront section on the dashboard.
     */
    readonly cloudFrontDistributionIdSsmPath?: string;

    /**
     * SSM path containing the NLB full name for CloudWatch metrics.
     * Format of the stored value: `net/{lb-name}/{lb-id}`
     *
     * NOTE: The NLB full name contains a random suffix generated by AWS
     * at creation time, which is not available at CDK synth time.
     * Resolved at deploy time via `ssm.StringParameter.valueForStringParameter`.
     */
    readonly nlbFullNameSsmPath?: string;

    /**
     * Self-healing pipeline Lambda configuration.
     * When provided, the Operations Dashboard includes agent + tool metrics.
     */
    readonly selfHealingConfig?: OpsDashboardSelfHealingConfig;
}

// =============================================================================
// STACK
// =============================================================================

/**
 * Kubernetes Observability Stack — Pre-deployment CloudWatch dashboard.
 *
 * Reads infrastructure references from SSM and creates a CloudWatch
 * dashboard covering EC2, NLB, Step Functions, Lambda, and CloudFront.
 */
export class KubernetesObservabilityStack extends cdk.Stack {
    /** The infrastructure dashboard construct */
    public readonly dashboard: InfrastructureDashboard;

    constructor(scope: Construct, id: string, props: KubernetesObservabilityStackProps) {
        super(scope, id, {
            ...props,
            description: `Pre-deployment CloudWatch dashboard for K8s infrastructure - ${props.targetEnvironment}`,
        });

        const { namePrefix, ssmPrefix } = props;

        // =================================================================
        // Resolve ASG names from naming convention
        //
        // ASG names follow the pattern: {namePrefix}-{role}
        // These are set by AutoScalingGroupConstruct via the instanceName prop.
        // =================================================================
        const controlPlaneAsgName = `${namePrefix}-asg`;
        const appWorkerAsgName = `${namePrefix}-worker-asg`;
        const monitoringWorkerAsgName = `${namePrefix}-mon-worker-asg`;
        const argoCdWorkerAsgName = `${namePrefix}-argocd-worker-asg`;

        // =================================================================
        // Resolve NLB full name from SSM (deploy-time resolution)
        //
        // NLB name is set in base-stack.ts: `${namePrefix}-nlb`
        // CloudWatch NLB metrics require the full name format: net/{name}/{id}
        // Resolved via SSM at deploy time — scoped to `this` (the Stack).
        // Falls back to a placeholder if no SSM path is provided.
        // =================================================================
        const nlbName = props.nlbFullNameSsmPath
            ? ssm.StringParameter.valueForStringParameter(this, props.nlbFullNameSsmPath)
            : `net/${namePrefix}-nlb/placeholder`;

        // =================================================================
        // Resolve CloudFront distribution ID from SSM (deploy-time resolution)
        // =================================================================
        const cloudFrontDistributionId = props.cloudFrontDistributionIdSsmPath
            ? ssm.StringParameter.valueForStringParameter(this, props.cloudFrontDistributionIdSsmPath)
            : undefined;

        // =================================================================
        // Dashboard Construct
        // =================================================================
        this.dashboard = new InfrastructureDashboard(this, 'InfraDashboard', {
            namePrefix,
            region: this.region,
            ec2: {
                controlPlaneAsgName,
                appWorkerAsgName,
                monitoringWorkerAsgName,
                argoCdWorkerAsgName,
            },
            nlb: {
                loadBalancerFullName: nlbName,
            },
            cloudFront: cloudFrontDistributionId
                ? { distributionId: cloudFrontDistributionId }
                : undefined,
        });

        // =================================================================
        // Stack Outputs
        // =================================================================
        new cdk.CfnOutput(this, 'DashboardName', {
            value: this.dashboard.dashboardName,
            description: 'CloudWatch Dashboard name',
        });

        new cdk.CfnOutput(this, 'DashboardUrl', {
            value: `https://${this.region}.console.aws.amazon.com/cloudwatch/home?region=${this.region}#dashboards:name=${this.dashboard.dashboardName}`,
            description: 'Direct link to the Infrastructure Dashboard',
        });

        // =================================================================
        // Operations Dashboard — Deployment Execution Traceability
        //
        // Separate dashboard for runtime visibility: AMI builds, SSM
        // bootstrap, drift enforcement, and self-healing pipeline.
        // =================================================================
        const opsDashboard = new OperationsDashboard(this, 'OpsDashboard', {
            namePrefix,
            region: this.region,
            ssmPrefix,
            selfHealing: props.selfHealingConfig,
        });

        new cdk.CfnOutput(this, 'OpsDashboardName', {
            value: opsDashboard.dashboardName,
            description: 'CloudWatch Operations Dashboard name',
        });

        new cdk.CfnOutput(this, 'OpsDashboardUrl', {
            value: `https://${this.region}.console.aws.amazon.com/cloudwatch/home?region=${this.region}#dashboards:name=${opsDashboard.dashboardName}`,
            description: 'Direct link to the Operations Dashboard',
        });
    }
}
