helm:
  parameters:
  - name: image.tag
    value: e889ccc807c84e2b68132ee6266e2c94e895c71f-r1
    forcestring: true
  - name: image.repository
    value: 771826808455.dkr.ecr.eu-west-1.amazonaws.com/wiki-mcp
    forcestring: true
